# Generated by Django 2.0.4 on 2018-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('EnvTemp', 'Environment Temp'), ('EnvHumidity', 'Humidity'), ('WaterTempFishTank', 'Fish Tank Water Temp'), ('WaterTempSumpTank', 'Sump Tank Water Temp'), ('WaterPH', 'Water pH'), ('WaterLevelLow', 'Low Water Level'), ('WaterLevelFull', 'Full Water Level'), ('IsFilling', 'Water Filling'), ('WaterFlowFishTank', 'Fish Tank Water Flow'), ('WaterFlowMain', 'Main Water Flow'), ('WaterFlowVertGrow', 'Vertical Water Flow'), ('WaterFlowHorizGrow', 'Horizontal Water Flow')], default='EnvTemp', max_length=10)),
                ('threshold', models.CharField(max_length=10)),
                ('criteria', models.CharField(choices=[('greater', 'greater'), ('less', 'less')], default='greater', max_length=10)),
                ('alert', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='on', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='envhumidity',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='envtemp',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='isfilling',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='waterflowfishtank',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='waterflowhorizgrow',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='waterflowmain',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='waterflowvertgrow',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='waterlevelfull',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='waterlevellow',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='waterph',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='watertempfishtank',
            old_name='isalert',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='watertempsumptank',
            old_name='isalert',
            new_name='alert',
        ),
    ]
