# Generated by Django 2.0.4 on 2018-06-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20180610_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsetting',
            name='sensor',
            field=models.CharField(choices=[('EnvTemp', 'EnvTemp'), ('EnvHumidity', 'EnvHumidity'), ('WaterTempFishTank', 'WaterTempFishTank'), ('WaterTempSumpTank', 'WaterTempSumpTank'), ('WaterPH', 'WaterPH'), ('WaterLevelLow', 'WaterLevelLow'), ('WaterLevelFull', 'WaterLevelFull'), ('IsFilling', 'IsFilling'), ('WaterFlowFishTank', 'WaterFlowFishTank'), ('WaterFlowMain', 'WaterFlowMain'), ('WaterFlowVertGrow', 'WaterFlowVertGrow'), ('WaterFlowHorizGrow', 'WaterFlowHorizGrow')], default='EnvTemp', max_length=30, primary_key=True, serialize=False),
        ),
    ]
