# Generated by Django 2.0.4 on 2018-06-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20180610_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertsetting',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='alertsetting',
            name='threshold',
        ),
    ]
