# Generated by Django 2.0.4 on 2018-06-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20180611_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsetting',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
