# Generated by Django 2.0.4 on 2018-06-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20180611_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='envhumidity',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='envhumidity',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='envhumidity',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
    ]
