# Generated by Django 2.0.4 on 2018-06-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20180611_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='envtemp',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='envtemp',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='envtemp',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='isfilling',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='isfilling',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='isfilling',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowfishtank',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowfishtank',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowfishtank',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowhorizgrow',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowhorizgrow',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowhorizgrow',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowmain',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowmain',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowmain',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowvertgrow',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowvertgrow',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterflowvertgrow',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='waterlevelfull',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterlevelfull',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterlevelfull',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='waterlevellow',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterlevellow',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterlevellow',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='waterph',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterph',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='waterph',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='watertempfishtank',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='watertempfishtank',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='watertempfishtank',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
        migrations.AddField(
            model_name='watertempsumptank',
            name='lowerlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='watertempsumptank',
            name='upperlimit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='watertempsumptank',
            name='withinlimit',
            field=models.CharField(default='YES', max_length=10),
        ),
    ]
