# Generated by Django 2.0.4 on 2018-06-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20180611_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsetting',
            name='alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertsetting',
            name='lowerlimit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='alertsetting',
            name='upperlimit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='envhumidity',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
