# Generated by Django 2.0.4 on 2018-06-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_auto_20180611_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockAlertSetting',
            fields=[
                ('sensor', models.CharField(choices=[('envtemp', 'EnvTemp'), ('envhumidity', 'EnvHumidity'), ('watertempfishtank', 'WaterTempFishTank'), ('watertempsumptank', 'WaterTempSumpTank'), ('waterph', 'WaterPH'), ('isfilling', 'IsFilling'), ('waterlevellow', 'WaterLevelLow'), ('waterlevelfull', 'WaterLevelFull'), ('waterflowfishtank', 'WaterFlowFishTank'), ('waterflowmain', 'WaterFlowMain'), ('waterflowvertgrow', 'WaterFlowVertGrow'), ('waterflowhorizgrow', 'WaterFlowHorizGrow')], default='envtemp', max_length=30, primary_key=True, serialize=False)),
                ('alert', models.BooleanField(default=True)),
                ('lowerlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('upperlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
