# Generated by Django 2.0.4 on 2018-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_mockalertsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockalertsetting',
            name='slider',
            field=models.CharField(default='<div>', max_length=100),
        ),
    ]
