# Generated by Django 2.0.4 on 2018-06-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_mockalertsetting_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockalertsetting',
            name='label',
            field=models.CharField(default='label', max_length=30),
        ),
    ]
