# Generated by Django 2.0.4 on 2018-06-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_mockalertsetting_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockalertsetting',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
