# Generated by Django 2.0.4 on 2018-06-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_mockalertsetting_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsetting',
            name='label',
            field=models.CharField(default='label', max_length=30),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='slider',
            field=models.CharField(default='<div>', max_length=100),
        ),
    ]
