# Generated by Django 2.0.4 on 2018-06-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_auto_20180624_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
