# Generated by Django 2.0.4 on 2018-06-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0026_waterlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockAlertSetting',
        ),
    ]
