# Generated by Django 2.0.4 on 2018-06-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_delete_mockalertsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MH0001_HUMIDITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alert', models.BooleanField(default=True)),
                ('lowerlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('upperlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('withinlimit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MH0001_TEMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alert', models.BooleanField(default=True)),
                ('lowerlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('upperlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('withinlimit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MH0002_HUMIDITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alert', models.BooleanField(default=True)),
                ('lowerlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('upperlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('withinlimit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MH0002_TEMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alert', models.BooleanField(default=True)),
                ('lowerlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('upperlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('withinlimit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MH0003_HUMIDITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alert', models.BooleanField(default=True)),
                ('lowerlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('upperlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('withinlimit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MH0003_TEMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alert', models.BooleanField(default=True)),
                ('lowerlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('upperlimit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('withinlimit', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EnvHumidity',
        ),
        migrations.DeleteModel(
            name='EnvTemp',
        ),
        migrations.DeleteModel(
            name='IsFilling',
        ),
        migrations.DeleteModel(
            name='WaterFlowFishTank',
        ),
        migrations.DeleteModel(
            name='WaterFlowHorizGrow',
        ),
        migrations.DeleteModel(
            name='WaterFlowMain',
        ),
        migrations.DeleteModel(
            name='WaterFlowVertGrow',
        ),
        migrations.DeleteModel(
            name='WaterLevel',
        ),
        migrations.DeleteModel(
            name='WaterLevelFull',
        ),
        migrations.DeleteModel(
            name='WaterLevelLow',
        ),
        migrations.DeleteModel(
            name='WaterPH',
        ),
        migrations.DeleteModel(
            name='WaterTempFishTank',
        ),
        migrations.DeleteModel(
            name='WaterTempSumpTank',
        ),
        migrations.AlterField(
            model_name='alertsetting',
            name='sensor',
            field=models.CharField(choices=[('mh0001_temp', 'MH0001_TEMP'), ('mh0001_humidity', 'MH0001_HUMIDITY'), ('mh0001_temp', 'MH0002_TEMP'), ('mh0001_humidity', 'MH0002_HUMIDITY'), ('mh0001_temp', 'MH0003_TEMP'), ('mh0001_humidity', 'MH0003_HUMIDITY')], default='mh0001_temp', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alertsetting',
            name='slider',
            field=models.CharField(default='slider', max_length=100),
        ),
    ]
