# Generated by Django 2.0.4 on 2018-06-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_auto_20180628_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsetting',
            name='sensor',
            field=models.CharField(choices=[('mh0001_temp', 'MH0001_TEMP'), ('mh0001_humidity', 'MH0001_HUMIDITY'), ('mh0002_temp', 'MH0002_TEMP'), ('mh0002_humidity', 'MH0002_HUMIDITY'), ('mh0003_temp', 'MH0003_TEMP'), ('mh0003_humidity', 'MH0003_HUMIDITY')], default='mh0001_temp', max_length=30, primary_key=True, serialize=False),
        ),
    ]
